allprojects {
    group = 'inceris.rcc'
    version = '1.0.0'
    repositories {
        mavenCentral()
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://maven.fabricmc.net/' }
    }
}
subprojects { p ->
    if (p.name != 'fabric') {
        apply plugin: 'java'
        java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }
        tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
    }
}
